server:
  port: 8099
spring:
  datasource:
    url: jdbc:mysql://192.168.0.99:3307/panzi-1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root #数据库用户
    password: 1hbl#QThztwcs #数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      initial-size: 5
      max-idle: 10
      min-idle: 5
      max-wait-millis: 1000