server:
  port: 8099
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learn_data?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    username: root #数据库用户
    password: mysql@123 #数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      initial-size: 5
      max-idle: 10
      min-idle: 5
      max-wait-millis: 1000
  data:
    redis: #  Redis 配置
      database: 1 # 数据库索引（默认0）
      host: 127.0.0.1
      port: 6379 # 默认链接端口
      lettuce:
        pool:
          max-wait: -1 # 最大阻塞等待时间（使用负值没有限制）默认为 -1
          max-idle: 8  # 链接池中最大空闲连接 默认 8
          min-idle: 0
          max-active: 8
      timeout: 5000ms

  mail: # 邮箱配置
    host: smtp.163.com # smtp.163.com
    username: xuzhenshanvip@163.com # 163邮箱地址
    password: CVAZCOJUUDPYIMEG # 注意这里不是邮箱密码，而是SMTP授权密码
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable: true
        imap:
          ssl:
            socketFactory:
              fallback: false

  upload-config: # 文件保存的根目录，所有文件都保存在整个文件夹下
    root-folder: E:\Test File

  user-defined: # 项目自定义配置
    swagger-enable: true # swagger 的 enable 配置

  payment:
    # 支付宝支付配置
    alipay:
      # 支付宝网关
      gateway-url:
      # 支付宝appid
      appid:
      # 支付宝公钥
      publicKey:
      # 商品私钥
      merchantPrivateKey:
    # 微信支付配置
    wechat:
      # 微信商户号
      mchId:
      # 微信公众号 appid
      appid:
      #微信公众平台appSecret
      appSecret:
      # v3 接口ca证书 apiclient_key.pem
      privateKey:
      # 微信支付证书
      wechatPayKey:
      # 商户证书序列号CA证书
      mchSerialNo:
      # apiV3 密钥
      apiV3Key: